export interface TemplateItem {
  name: string;
  state: string;
  type: string;
  milestones: { label: string; category: string }[];
  documents: { name: string; category: string }[];
}

export const CHECKLIST_TEMPLATES: TemplateItem[] = [
  {
    name: 'CT Purchase',
    state: 'CT',
    type: 'Purchase',
    milestones: [
      { label: 'Contract Signed', category: 'Contract' },
      { label: 'Attorney Review Period Ends', category: 'Contract' },
      { label: 'Home Inspection', category: 'Inspection' },
      { label: 'Radon Test', category: 'Inspection' },
      { label: 'Well/Septic Inspection', category: 'Inspection' },
      { label: 'Mortgage Application', category: 'Financing' },
      { label: 'Appraisal Ordered', category: 'Financing' },
      { label: 'Mortgage Commitment', category: 'Financing' },
      { label: 'Title Search Complete', category: 'Closing' },
      { label: 'Final Walkthrough', category: 'Closing' },
      { label: 'Closing', category: 'Closing' },
    ],
    documents: [
      { name: 'Purchase Agreement', category: 'Contracts' },
      { name: 'Property Disclosure', category: 'Disclosures' },
      { name: 'Lead Paint Disclosure', category: 'Disclosures' },
      { name: 'Home Inspection Report', category: 'Inspections' },
      { name: 'Radon Test Results', category: 'Inspections' },
      { name: 'Appraisal Report', category: 'Financing' },
      { name: 'Mortgage Commitment Letter', category: 'Financing' },
      { name: 'Title Search', category: 'Title' },
      { name: 'Title Insurance Policy', category: 'Title' },
      { name: 'Closing Disclosure', category: 'Closing' },
      { name: 'Deed', category: 'Closing' },
    ],
  },
  {
    name: 'CT Listing',
    state: 'CT',
    type: 'Sale',
    milestones: [
      { label: 'Listing Agreement Signed', category: 'Contract' },
      { label: 'Photos & Virtual Tour', category: 'Contract' },
      { label: 'Listed on MLS', category: 'Contract' },
      { label: 'Offer Accepted', category: 'Contract' },
      { label: 'Attorney Review Period', category: 'Contract' },
      { label: 'Buyer Inspection', category: 'Inspection' },
      { label: 'Appraisal', category: 'Financing' },
      { label: 'Buyer Mortgage Commitment', category: 'Financing' },
      { label: 'Title Cleared', category: 'Closing' },
      { label: 'Final Walkthrough', category: 'Closing' },
      { label: 'Closing', category: 'Closing' },
    ],
    documents: [
      { name: 'Listing Agreement', category: 'Contracts' },
      { name: 'Property Disclosure', category: 'Disclosures' },
      { name: 'Lead Paint Disclosure', category: 'Disclosures' },
      { name: 'Purchase Agreement', category: 'Contracts' },
      { name: 'Closing Disclosure', category: 'Closing' },
    ],
  },
  {
    name: 'FL Purchase',
    state: 'FL',
    type: 'Purchase',
    milestones: [
      { label: 'Contract Executed', category: 'Contract' },
      { label: 'Earnest Money Deposited', category: 'Contract' },
      { label: 'Home Inspection', category: 'Inspection' },
      { label: 'WDO (Termite) Inspection', category: 'Inspection' },
      { label: '4-Point Inspection', category: 'Inspection' },
      { label: 'Wind Mitigation', category: 'Inspection' },
      { label: 'Appraisal Ordered', category: 'Financing' },
      { label: 'Loan Approval', category: 'Financing' },
      { label: 'Title Search & Insurance', category: 'Closing' },
      { label: 'Survey', category: 'Closing' },
      { label: 'Final Walkthrough', category: 'Closing' },
      { label: 'Closing', category: 'Closing' },
    ],
    documents: [
      { name: 'FAR/BAR Contract', category: 'Contracts' },
      { name: 'Seller Disclosure', category: 'Disclosures' },
      { name: 'HOA Documents', category: 'Disclosures' },
      { name: 'Home Inspection Report', category: 'Inspections' },
      { name: 'WDO Report', category: 'Inspections' },
      { name: '4-Point Inspection', category: 'Inspections' },
      { name: 'Wind Mitigation Report', category: 'Inspections' },
      { name: 'Appraisal Report', category: 'Financing' },
      { name: 'Survey', category: 'Title' },
      { name: 'Title Commitment', category: 'Title' },
      { name: 'Closing Disclosure', category: 'Closing' },
    ],
  },
  {
    name: 'FL Listing',
    state: 'FL',
    type: 'Sale',
    milestones: [
      { label: 'Listing Agreement Signed', category: 'Contract' },
      { label: 'Photos & Marketing', category: 'Contract' },
      { label: 'Listed on MLS', category: 'Contract' },
      { label: 'Offer Accepted', category: 'Contract' },
      { label: 'Buyer Due Diligence Period', category: 'Inspection' },
      { label: 'Buyer Loan Approval', category: 'Financing' },
      { label: 'Title Cleared', category: 'Closing' },
      { label: 'Closing', category: 'Closing' },
    ],
    documents: [
      { name: 'Listing Agreement', category: 'Contracts' },
      { name: 'Seller Disclosure', category: 'Disclosures' },
      { name: 'FAR/BAR Contract', category: 'Contracts' },
      { name: 'Closing Disclosure', category: 'Closing' },
    ],
  },
];
