// Mock data for development without database

export const MOCK_USER = {
  id: "user_001",
  email: "agent@closepilot.ai",
  name: "Demo Agent",
  phone: "(203) 555-0188",
  licenseNumber: "CT-REB.0795xxx",
  brokerage: "Premier Realty Group",
}

export const MOCK_TRANSACTIONS = [
  {
    id: "tx_001",
    propertyAddress: "252 Shelton St, Bridgeport, CT 06608",
    status: "active",
    buyerName: "Ayisha Wint",
    sellerName: "Ruth Cogdell & Malika Tulloch",
    purchasePrice: 300000,
    effectiveDate: "2026-01-22",
    closingDate: "2026-03-13",
    contractType: "CT SmartMLS Standard Form",
    agentId: "user_001",
    createdAt: "2026-01-22",
    milestones: [
      { id: "ms_001", name: "Contract Executed / Initial Deposit ($3,000)", type: "deposit", dueDate: "2026-01-22", status: "completed", remindersSent: 0 },
      { id: "ms_002", name: "Attorney Review Deadline", type: "attorney_review", dueDate: "2026-01-29", status: "completed", remindersSent: 1 },
      { id: "ms_003", name: "Inspection Completion Deadline", type: "inspection", dueDate: "2026-02-02", status: "completed", remindersSent: 2 },
      { id: "ms_004", name: "Inspection Objection Deadline", type: "inspection", dueDate: "2026-02-04", status: "completed", remindersSent: 1 },
      { id: "ms_005", name: "Additional Deposit Due ($7,500)", type: "deposit", dueDate: "2026-02-06", status: "completed", remindersSent: 2 },
      { id: "ms_006", name: "Title Search Completion", type: "title", dueDate: "2026-02-17", status: "pending", remindersSent: 0 },
      { id: "ms_007", name: "Title Objection Deadline", type: "title", dueDate: "2026-02-19", status: "pending", remindersSent: 0 },
      { id: "ms_008", name: "Mortgage Commitment Deadline", type: "loan_approval", dueDate: "2026-02-27", status: "pending", remindersSent: 0 },
      { id: "ms_009", name: "CLOSING DATE — Fairfield County", type: "closing", dueDate: "2026-03-13", status: "pending", remindersSent: 0 },
    ],
    parties: [
      { id: "p_001", role: "buyer", name: "Ayisha Wint", email: "awint@email.com", phone: "(203) 555-0101", company: null },
      { id: "p_002", role: "seller", name: "Ruth Cogdell", email: "rcogdell@email.com", phone: "(203) 555-0201", company: null },
      { id: "p_003", role: "seller", name: "Malika Tulloch", email: "mtulloch@email.com", phone: "(203) 555-0202", company: null },
      { id: "p_004", role: "listing_agent", name: "Valerie King", email: "valerie.king@kw.com", phone: "(203) 555-0142", company: "Keller Williams Realty Prtnrs" },
      { id: "p_005", role: "buyers_agent", name: "Demo Agent", email: "agent@closepilot.ai", phone: "(203) 555-0188", company: "Premier Realty Group" },
      { id: "p_006", role: "lender", name: "David Park", email: "dpark@mortgageco.com", phone: "(203) 555-0301", company: "First National Mortgage" },
      { id: "p_007", role: "attorney", name: "Michael Rosen", email: "mrosen@ctlaw.com", phone: "(203) 555-0401", company: "Rosen & Associates" },
    ],
    documents: [
      { id: "doc_001", name: "Purchase Agreement.pdf", uploadedAt: "2026-01-22" },
      { id: "doc_002", name: "Pre-Approval Letter.pdf", uploadedAt: "2026-01-22" },
    ],
  },
  {
    id: "tx_002",
    propertyAddress: "47 Prospect Ridge, Ridgefield, CT 06877",
    status: "pending_closing",
    buyerName: "Jennifer & Mark Walsh",
    sellerName: "Robert & Linda Martinez",
    purchasePrice: 615000,
    effectiveDate: "2026-01-05",
    closingDate: "2026-02-14",
    contractType: "CT SmartMLS Standard Form",
    agentId: "user_001",
    createdAt: "2026-01-05",
    milestones: [
      { id: "ms_101", name: "Contract Executed / Initial Deposit ($5,000)", type: "deposit", dueDate: "2026-01-05", status: "completed", remindersSent: 0 },
      { id: "ms_102", name: "Attorney Review Deadline", type: "attorney_review", dueDate: "2026-01-12", status: "completed", remindersSent: 1 },
      { id: "ms_103", name: "Inspection Completion Deadline", type: "inspection", dueDate: "2026-01-16", status: "completed", remindersSent: 2 },
      { id: "ms_104", name: "Inspection Objection Deadline", type: "inspection", dueDate: "2026-01-20", status: "completed", remindersSent: 1 },
      { id: "ms_105", name: "Additional Deposit Due ($10,000)", type: "deposit", dueDate: "2026-01-19", status: "completed", remindersSent: 2 },
      { id: "ms_106", name: "Title Search Completion", type: "title", dueDate: "2026-01-30", status: "completed", remindersSent: 1 },
      { id: "ms_107", name: "Mortgage Commitment Deadline", type: "loan_approval", dueDate: "2026-02-04", status: "completed", remindersSent: 2 },
      { id: "ms_108", name: "Final Walkthrough", type: "other", dueDate: "2026-02-13", status: "pending", remindersSent: 0 },
      { id: "ms_109", name: "CLOSING DATE — Fairfield County", type: "closing", dueDate: "2026-02-14", status: "pending", remindersSent: 0 },
    ],
    parties: [
      { id: "p_101", role: "buyer", name: "Jennifer Walsh", email: "jwalsh@email.com", phone: "(203) 555-1101", company: null },
      { id: "p_102", role: "buyer", name: "Mark Walsh", email: "mwalsh@email.com", phone: "(203) 555-1102", company: null },
      { id: "p_103", role: "seller", name: "Robert Martinez", email: "rmartinez@email.com", phone: "(203) 555-1201", company: null },
      { id: "p_104", role: "listing_agent", name: "Tom Bradley", email: "tbradley@compass.com", phone: "(203) 555-1142", company: "Compass CT" },
      { id: "p_105", role: "buyers_agent", name: "Demo Agent", email: "agent@closepilot.ai", phone: "(203) 555-0188", company: "Premier Realty Group" },
      { id: "p_106", role: "lender", name: "Amanda Ross", email: "aross@mortgage.com", phone: "(203) 555-1301", company: "Webster Bank Mortgage" },
      { id: "p_107", role: "attorney", name: "Sarah Klein", email: "sklein@ctlaw.com", phone: "(203) 555-1401", company: "Klein & Partners" },
    ],
    documents: [
      { id: "doc_101", name: "Purchase Agreement.pdf", uploadedAt: "2026-01-05" },
      { id: "doc_102", name: "Inspection Report.pdf", uploadedAt: "2026-01-15" },
      { id: "doc_103", name: "Mortgage Commitment Letter.pdf", uploadedAt: "2026-02-03" },
    ],
  },
  {
    id: "tx_003",
    propertyAddress: "189 Tokeneke Rd, Darien, CT 06820",
    status: "new",
    buyerName: "David & Karen Liu",
    sellerName: "Estate of William Foster",
    purchasePrice: 925000,
    effectiveDate: "2026-02-05",
    closingDate: "2026-04-01",
    contractType: "CT SmartMLS Standard Form",
    agentId: "user_001",
    createdAt: "2026-02-05",
    milestones: [
      { id: "ms_201", name: "Contract Executed / Initial Deposit ($15,000)", type: "deposit", dueDate: "2026-02-05", status: "completed", remindersSent: 0 },
      { id: "ms_202", name: "Attorney Review Deadline (5 business days)", type: "attorney_review", dueDate: "2026-02-12", status: "pending", remindersSent: 0 },
      { id: "ms_203", name: "Inspection Completion Deadline", type: "inspection", dueDate: "2026-02-19", status: "pending", remindersSent: 0 },
      { id: "ms_204", name: "Inspection Objection Deadline", type: "inspection", dueDate: "2026-02-23", status: "pending", remindersSent: 0 },
      { id: "ms_205", name: "Additional Deposit Due ($25,000)", type: "deposit", dueDate: "2026-02-19", status: "pending", remindersSent: 0 },
      { id: "ms_206", name: "Title Search Completion", type: "title", dueDate: "2026-03-05", status: "pending", remindersSent: 0 },
      { id: "ms_207", name: "Title Objection Deadline", type: "title", dueDate: "2026-03-09", status: "pending", remindersSent: 0 },
      { id: "ms_208", name: "Mortgage Commitment Deadline", type: "loan_approval", dueDate: "2026-03-19", status: "pending", remindersSent: 0 },
      { id: "ms_209", name: "Final Walkthrough", type: "other", dueDate: "2026-03-31", status: "pending", remindersSent: 0 },
      { id: "ms_210", name: "CLOSING DATE — Fairfield County", type: "closing", dueDate: "2026-04-01", status: "pending", remindersSent: 0 },
    ],
    parties: [
      { id: "p_201", role: "buyer", name: "David Liu", email: "dliu@email.com", phone: "(203) 555-2101", company: null },
      { id: "p_202", role: "buyer", name: "Karen Liu", email: "kliu@email.com", phone: "(203) 555-2102", company: null },
      { id: "p_203", role: "seller", name: "Estate of William Foster (c/o Attorney)", email: "probate@ctlawfirm.com", phone: "(203) 555-2201", company: "Foster & Associates Law" },
      { id: "p_204", role: "listing_agent", name: "Rachel Green", email: "rgreen@sothebys.com", phone: "(203) 555-2142", company: "Sotheby's Intl Realty" },
      { id: "p_205", role: "buyers_agent", name: "Demo Agent", email: "agent@closepilot.ai", phone: "(203) 555-0188", company: "Premier Realty Group" },
      { id: "p_206", role: "attorney", name: "James Whitfield", email: "jwhitfield@ctlaw.com", phone: "(203) 555-2401", company: "Whitfield & Shaw" },
    ],
    documents: [
      { id: "doc_201", name: "Purchase Agreement.pdf", uploadedAt: "2026-02-05" },
    ],
  },
]
